[WIP] feat: create sample parameterised svg
gs-gs/project-vckit pull request #19
Opened 2023-05-21 13:52 UTC by namhoang1604

## Linked Issue

- #17

## Type of change

- [x] Implement the parameterized SVG renderer (non-breaking change which adds functionality)
- [x] This change requires a documentation update (storybook and example apps)
- [x] This change requires the unit test and e2e test update

## Screenshot

<img width="1501" alt="image" src="https://github.com/gs-gs/project-vckit/assets/13606809/a6767b9d-9c6b-4a7a-a844-9068721a058d">
<img width="1507" alt="image" src="https://github.com/gs-gs/project-vckit/assets/13606809/8b197b99-98cb-47b3-a8b6-3d8f800cda3a">
<img width="1504" alt="image" src="https://github.com/gs-gs/project-vckit/assets/13606809/1155cae4-7fc9-4af0-a7f1-5a0eb8d84974">

2023-05-22 11:05 UTC, toannvit requested changes

2023-05-22 11:05 UTC, toannvit commented on packages/vckit-oa-renderers/application/app.tsx
> +              source="http://localhost:3000"
maybe move this to env file or if it's mock , bring it to top of the file

2023-05-22 11:06 UTC, toannvit commented
LGTM except for one small change

2023-05-23 02:24 UTC, namhoang1604 commented
Close the PR to move to https://github.com/uncefact/project-vckit/pull/73

2023-05-23 02:24 UTC, closed without merging